# Generated by Django 4.2.5 on 2023-09-10 06:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_objekta', models.CharField(max_length=255)),
                ('ps_br', models.CharField(max_length=10, null=True)),
                ('e_br', models.CharField(max_length=10, null=True)),
                ('tip_objekta', models.IntegerField(null=True)),
                ('lucka_kapetanija', models.CharField(max_length=50, null=True)),
                ('fotografija', models.URLField(null=True)),
                ('id_ais', models.CharField(max_length=50, null=True)),
                ('simbol_oznaka', models.URLField(null=True)),
                ('lokacija', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
