# Generated by Django 4.2.5 on 2023-09-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyobject',
            name='e_br',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='safetyobject',
            name='fotografija',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='safetyobject',
            name='id_ais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='safetyobject',
            name='lucka_kapetanija',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='safetyobject',
            name='ps_br',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='safetyobject',
            name='simbol_oznaka',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='safetyobject',
            name='tip_objekta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
