# Generated by Django 4.2.5 on 2023-09-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_safetyobject_e_br_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyobject',
            name='fotografija',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='safetyobject',
            name='simbol_oznaka',
            field=models.CharField(blank=True, null=True),
        ),
    ]
